### ISSUE TITLE
Prompt that you have no permission

### ISSUE THREAD

**Issue by chifandeyu** [Kyle-Ye/MenuHelperApp#2]
mac MINI M1，macOS 12.3.1
![image](https://user-images.githubusercontent.com/15946864/201288338-c93c7fef-0b56-4d79-a339-ef5df85cfe41.png)

**Comment by Kyle-Ye** [comment]
点击OK即可，这个弹窗是系统弹出的，如果没有文件夹权限，除了这个窗口外应该还会有一个OpenPanel，在系统的OpenPanel里选择希望授权的文件夹（默认会是当前文件夹）然后点击"打开"即可完成授权。

> https://github.com/Kyle-Ye/MenuHelper/blob/4bccfe38031f8a7cb6f26e37155cc4abe1038340/MenuHelperExtension/MenuItemClickable.swift#LL26
> 具体逻辑在这里：没有权限的话会打开失败，进入catch部分
> 您也可以打开console.app，过滤筛选本App的日志查看更多信息

另一种方式是"打开设置面板"-"文件夹"Tab中手动选择文件夹授权。

通过Github和App Store渠道发布的 MenuHelper 均为沙盒App，对您的用户文件夹默认没有任何访问权限。

如果不希望受到改限制，可以手动Build并去掉沙盒限制。后续也会在Github渠道发布版本增加一个非沙盒版本。
